In [2]:
!pip install numpy

In [4]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

type(arr)

[1 2 3]


numpy.ndarray

# #zero D Array

In [5]:
import numpy as np

In [6]:
a = np.array(55)

In [7]:
a

array(55)

In [8]:
type(a)

numpy.ndarray

In [9]:
a.ndim

0

In [12]:
b = np.array([1,2,3,4])

In [13]:
b.ndim

1

# 2D Array

In [14]:
c = np.array([[1,2,3],[7,8,9]])

In [15]:
c

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
c.ndim

2

# 3d Array

In [23]:
d = np.array([[[1,2,3],[4,5,6]],[[5,6,8],[4,5,3]]])

In [24]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 8],
        [4, 5, 3]]])

In [25]:
d.ndim

3

# shape array

In [26]:
import numpy as np
a= np.array([1,2,3,4,5])
a.shape

(5,)

In [28]:
b=np.array([[1,2,3,4],[5,6,4,7]])
b.shape

(2, 4)

In [30]:
c= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new =c.reshape(4,3)
new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
c.shape

(12,)

In [32]:
new.shape

(4, 3)

In [33]:
new_arr2 = c.reshape(2,3,2)
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [34]:
new_arr2.shape

(2, 3, 2)

In [36]:
twoD_array = np.array([[1,2,3],[4,5,6]])

flatten_array = twoD_array.reshape(-1)


In [37]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [38]:
flatten_array.shape

(6,)

# Array indexing 

In [39]:
import numpy as np

In [40]:
a=np.array([3,4,5,6])

In [41]:
a

array([3, 4, 5, 6])

In [43]:
a.ndim

1

In [45]:
a[0]

3

In [46]:
a[2]

5

In [47]:
a[2]+a[0]

8

# 2D Array

In [48]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Access element from 2nd row and 5th column

In [49]:
b[1,4]

10

In [50]:
b[0,2]

3

# Array ITerating

In [55]:
arr = np.array([1,2,3])

In [56]:
for x in arr:
    print(x)

1
2
3


In [57]:
arr2 =np.array([[1,2,3],[4,5,6]])

In [58]:
for j in arr2:
    print(j)

[1 2 3]
[4 5 6]


In [60]:
for j in arr2:
    for b in j:
        print(b)

1
2
3
4
5
6


# Array Slicing

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [62]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[1:5]

array([2, 3, 4, 5])

In [64]:
a[2:7]

array([3, 4, 5, 6, 7])

In [65]:
a[4:]

array([5, 6, 7, 8, 9])

In [66]:
a[:5]

array([1, 2, 3, 4, 5])

In [67]:
a[1:6:2]

array([2, 4, 6])

# Slice a 2d array

In [68]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [69]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [70]:
b[1,1:4]

array([7, 8, 9])

In [71]:
b[0,0:3]

array([1, 2, 3])

# Scearch and Sort

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,8,5,10,20,1])

In [7]:
x=np.where(a==1)

In [6]:
y = np.where(a==4)

In [9]:
y

(array([3], dtype=int64),)

In [10]:
x

(array([0, 9], dtype=int64),)

In [78]:
ans = np.where(a%2==0)

In [79]:
ans

(array([1, 3, 5, 7, 8], dtype=int64),)

In [80]:
np.sort(a)

array([ 1,  1,  2,  3,  4,  5,  5,  8, 10, 20])

In [81]:
a2=np.array([44,12,90,76,55])

In [84]:
np.sort(a2)

array([12, 44, 55, 76, 90])

In [85]:
a3 = np.array(["mango","papaya","apple","orange"])

In [86]:
np.sort(a3)

array(['apple', 'mango', 'orange', 'papaya'], dtype='<U6')